# Generated by Django 5.2.5 on 2025-08-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
