# Generated by Django 5.2.5 on 2025-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_article_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
